name: CICD
on: [push]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - name: Lint code
      run: sudo apt-get golangci-lint
           golangci-lint run
    - name: Test
      run: go test
    
        
